dataset:
  cluster_configs:
    - &dataset_default
      dataset: cifar10_torch
      distribution:
        # client_weights:
        #   - 0.5
        #   - 0.5
        extra_params:
          diritchlet:
            alpha: 1.0
            seed: 10
        train_test_split:
          train: 0.8
          test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.0001
      batch_size: 256
      local_epochs: 5
      extra_params:
        fed_prox:
          mu: 0.01
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      batch_size: 256
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    strategy: cifar10_cnn_fedavg

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *dataset_default

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *dataset_default

clients:
  node_1:
    <<: *def_client
  node_2:
    <<: *def_client
  node_3:
    <<: *def_client
  node_4:
    <<: *def_client
  node_5:
    <<: *def_client
  node_6:
    <<: *def_client
  node_7:
    <<: *def_client
  node_8:
    <<: *def_client

workers:
  node_0:
    <<: *def_worker
  node_1:
    <<: *def_worker
  node_2:
    <<: *def_worker
  node_3:
    <<: *def_worker
  node_4:
    <<: *def_worker
  node_5:
    <<: *def_worker
  node_6:
    <<: *def_worker
  node_7:
    <<: *def_worker
  node_8:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - cluster_0_0
      - cluster_0_1
    workers:
      - node_0
      - node_2
      - node_8
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_0:
    upstream_cluster: cluster_0
    clients:
      - cluster_0_0_0
      - cluster_0_0_1
    workers:
      - node_0
      - node_1
      - node_3
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_1:
    upstream_cluster: cluster_0
    clients:
      - cluster_0_1_0
      - cluster_0_1_1
    workers:
      - node_0
      - node_5
      - node_7
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_0_0:
    upstream_cluster: cluster_0_0
    clients:
      - node_1
      - node_2
    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_0_1:
    upstream_cluster: cluster_0_0
    clients:
      - node_3
      - node_4
    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_1_0:
    upstream_cluster: cluster_0_1
    clients:
      - node_5
      - node_6
    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

  cluster_0_1_1:
    upstream_cluster: cluster_0_1
    clients:
      - node_7
      - node_8
    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

job_params:
  rounds: 3
