dataset:
  cluster_configs:
    - &dataset_default
      dataset: cifar10_tensorflow
      distribution:
        # client_weights:
        #   - 0.5
        #   - 0.5
        extra_params:
          diritchlet:
            alpha: 0.1
            seed: 10
        train_test_split:
          train: 0.8
          test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.001
      batch_size: 256
      local_epochs: 2
      extra_params:
        fed_prox:
          mu: 0.01
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      batch_size: 256
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    strategy: cifar10_cnn_fedavg_tf

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *dataset_default

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *dataset_default

clients:
  node_0:
    <<: *def_client
  node_1:
    <<: *def_client

workers:
  node_0:
    <<: *def_worker
  node_1:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - node_0
      - node_1
    workers:
      - node_0

    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

job_params:
  rounds: 20
