dataset:
  cluster_configs:
    - &def_random_dist
      prep: cifar_def
      preprocessor: default
      distribution:
        distributor: random_dist # diritchlet_dist
        chunks:
          - 0.5
          - 0.5
        extra_params:
          diritchlet:
            alpha: 1.0
            seed: 10
      train_test_split:
        train: 0.8
        test: 0.2

    - &def_random_dist2
      prep: cifar_def
      preprocessor: default
      distribution:
        distributor: random_dist # diritchlet_dist
        chunks:
          - 0.1
          - 0.9
        extra_params:
          diritchlet:
            alpha: 1.0
            seed: 10
      train_test_split:
        train: 0.8
        test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.0001
      batch_size: 64
      local_epochs: 5
      extra_params:
        fed_prox:
          mu: 0.01
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      aggregator: fed_avg
      batch_size: 256
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    model_file: 10c_mobilenet
    parameter_mixer: default
    training_loop_file: cel_simple
    test_file: multi_cel_simple

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *def_random_dist

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *def_random_dist

clients:
  node_2:
    <<: *def_client
  node_3:
    <<: *def_client
  node_4:
    <<: *def_client
  node_5:
    <<: *def_client

workers:
  node_0:
    <<: *def_worker
  node_1:
    <<: *def_worker
  node_2:
    <<: *def_worker
  node_3:
    <<: *def_worker
  node_4:
    <<: *def_worker
  node_5:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - cluster_0_0
      - cluster_0_1
    workers:
      - node_0
      - node_1
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *def_random_dist

  cluster_0_0:
    upstream_cluster: cluster_0
    clients:
      - node_2
      - node_3
    workers:
      - node_0
      - node_2
      - node_3
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 2
    dataset_params:
      <<: *def_random_dist

  cluster_0_1:
    upstream_cluster: cluster_0
    clients:
      - node_4
      - node_5
    workers:
      - node_1
      - node_4
      - node_5
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *def_random_dist2

job_params:
  rounds: 50
