model_params: # model and training files and configs
  - &cifar10def
    model_file: cifar10CNN
    parameter_mixer: default
    training_loop_file: cel_simple
    test_file: multi_cel_simple

dataset: &dataset_params # dataset hyperparameters and configs
  - &dp_dir
  preprocessor: default
  distribution:
    distributor: diritchlet_dist
    extra_params:
      diritchlet:
        alpha: 0.5
        seed: 10
  train_test_split: # train test split config
    train: 0.8
    test: 0.2

train_params: # training parameters
  - &tp_cifar_def
  learning_rate: 0.0001
  batch_size: 64
  local_epochs: 1

  extra_params:
    lr_decay: 1

clients:
  client-0:
    model_params:
      <<: *cifar10def
    train_params:
      <<: *tp_cifar_def

  client-0:
    model_params:
      <<: *cifar10def
    train_params:
      <<: *tp_cifar_def
