dataset:
  cluster_configs:
    - &dataset_default
      dataset: mnist_sklearn
      distribution:
        # client_weights:
        #   - 0.5
        #   - 0.5
        extra_params:
          diritchlet:
            alpha: 1.0
            seed: 10
        train_test_split:
          train: 0.8
          test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.0001
      batch_size: 256
      local_epochs: 1
      extra_params:
        fed_prox:
          mu: 0.01
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      batch_size: 256
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    strategy: mnist_fedavg_sklearn

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *dataset_default

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *dataset_default

clients:
  node_0:
    <<: *def_client
  node_1:
    <<: *def_client
  node_2:
    <<: *def_client
  node_3:
    <<: *def_client
  node_4:
    <<: *def_client
  node_5:
    <<: *def_client
  node_6:
    <<: *def_client
  node_7:
    <<: *def_client
  node_8:
    <<: *def_client
  node_9:
    <<: *def_client
  node_10:
    <<: *def_client
  node_11:
    <<: *def_client
  node_12:
    <<: *def_client
  node_13:
    <<: *def_client
  node_14:
    <<: *def_client
  node_15:
    <<: *def_client
  node_16:
    <<: *def_client
  node_17:
    <<: *def_client
  node_18:
    <<: *def_client
  node_19:
    <<: *def_client
  node_20:
    <<: *def_client
  node_21:
    <<: *def_client
  node_22:
    <<: *def_client
  node_23:
    <<: *def_client
  node_24:
    <<: *def_client
  node_25:
    <<: *def_client
  node_26:
    <<: *def_client
  node_27:
    <<: *def_client
  node_28:
    <<: *def_client
  node_29:
    <<: *def_client
  node_30:
    <<: *def_client
  node_31:
    <<: *def_client
  node_32:
    <<: *def_client
  node_33:
    <<: *def_client
  node_34:
    <<: *def_client
  node_35:
    <<: *def_client
  node_36:
    <<: *def_client
  node_37:
    <<: *def_client
  node_38:
    <<: *def_client
  node_39:
    <<: *def_client
  node_40:
    <<: *def_client
  node_41:
    <<: *def_client
  node_42:
    <<: *def_client
  node_43:
    <<: *def_client
  node_44:
    <<: *def_client
  node_45:
    <<: *def_client
  node_46:
    <<: *def_client
  node_47:
    <<: *def_client
  node_48:
    <<: *def_client
  node_49:
    <<: *def_client
  node_50:
    <<: *def_client
  node_51:
    <<: *def_client
  node_52:
    <<: *def_client
  node_53:
    <<: *def_client
  node_54:
    <<: *def_client
  node_55:
    <<: *def_client
  node_56:
    <<: *def_client
  node_57:
    <<: *def_client
  node_58:
    <<: *def_client
  node_59:
    <<: *def_client
  node_60:
    <<: *def_client
  node_61:
    <<: *def_client
  node_62:
    <<: *def_client
  node_63:
    <<: *def_client
  node_64:
    <<: *def_client
  node_65:
    <<: *def_client
  node_66:
    <<: *def_client
  node_67:
    <<: *def_client
  node_68:
    <<: *def_client
  node_69:
    <<: *def_client
  node_70:
    <<: *def_client
  node_71:
    <<: *def_client
  node_72:
    <<: *def_client
  node_73:
    <<: *def_client
  node_74:
    <<: *def_client
  node_75:
    <<: *def_client
  node_76:
    <<: *def_client
  node_77:
    <<: *def_client
  node_78:
    <<: *def_client
  node_79:
    <<: *def_client
  node_80:
    <<: *def_client
  node_81:
    <<: *def_client
  node_82:
    <<: *def_client
  node_83:
    <<: *def_client
  node_84:
    <<: *def_client
  node_85:
    <<: *def_client
  node_86:
    <<: *def_client
  node_87:
    <<: *def_client
  node_88:
    <<: *def_client
  node_89:
    <<: *def_client
  node_90:
    <<: *def_client
  node_91:
    <<: *def_client
  node_92:
    <<: *def_client
  node_93:
    <<: *def_client
  node_94:
    <<: *def_client
  node_95:
    <<: *def_client
  node_96:
    <<: *def_client
  node_97:
    <<: *def_client
  node_98:
    <<: *def_client
  node_99:
    <<: *def_client

workers:
  node_0:
    <<: *def_worker
  node_1:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - node_0
      - node_1
      - node_2
      - node_3
      - node_4
      - node_5
      - node_6
      - node_7
      - node_8
      - node_9
      - node_10
      - node_11
      - node_12
      - node_13
      - node_14
      - node_15
      - node_16
      - node_17
      - node_18
      - node_19
      - node_20
      - node_21
      - node_22
      - node_23
      - node_24
      - node_25
      - node_26
      - node_27
      - node_28
      - node_29
      - node_30
      - node_31
      - node_32
      - node_33
      - node_34
      - node_35
      - node_36
      - node_37
      - node_38
      - node_39
      - node_40
      - node_41
      - node_42
      - node_43
      - node_44
      - node_45
      - node_46
      - node_47
      - node_48
      - node_49
      - node_50
      - node_51
      - node_52
      - node_53
      - node_54
      - node_55
      - node_56
      - node_57
      - node_58
      - node_59
      - node_60
      - node_61
      - node_62
      - node_63
      - node_64
      - node_65
      - node_66
      - node_67
      - node_68
      - node_69
      - node_70
      - node_71
      - node_72
      - node_73
      - node_74
      - node_75
      - node_76
      - node_77
      - node_78
      - node_79
      - node_80
      - node_81
      - node_82
      - node_83
      - node_84
      - node_85
      - node_86
      - node_87
      - node_88
      - node_89
      - node_90
      - node_91
      - node_92
      - node_93
      - node_94
      - node_95
      - node_96
      - node_97
      - node_98
      - node_99

    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

job_params:
  rounds: 20
