dataset:
  cluster_configs:
    - &dataset_default
      dataset: cifar10_torch
      distribution:
        extra_params:
          diritchlet:
            alpha: 10000.0
            seed: 10
        train_test_split:
          train: 0.8
          test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.001
      batch_size: 256
      local_epochs: 5
      extra_params:
        fed_prox:
          mu: 0.01
        moon:
          temp: 0.5
          mu: 5.0
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      batch_size: 256
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    strategy: cifar10_cnn_fedavg

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *dataset_default

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *dataset_default

clients:
  node_0:
    <<: *def_client
  node_1:
    <<: *def_client
  node_2:
    <<: *def_client
  node_3:
    <<: *def_client
  node_4:
    <<: *def_client
  node_5:
    <<: *def_client
  node_6:
    <<: *def_client
  node_7:
    <<: *def_client
  node_8:
    <<: *def_client
  node_9:
    <<: *def_client
  node_10:
    <<: *def_client
  node_11:
    <<: *def_client
  node_12:
    <<: *def_client
  node_13:
    <<: *def_client
  node_14:
    <<: *def_client
  node_15:
    <<: *def_client
  node_16:
    <<: *def_client
  node_17:
    <<: *def_client
  node_18:
    <<: *def_client
  node_19:
    <<: *def_client
  node_20:
    <<: *def_client
  node_21:
    <<: *def_client
  node_22:
    <<: *def_client
  node_23:
    <<: *def_client
  node_24:
    <<: *def_client
  node_25:
    <<: *def_client
  node_26:
    <<: *def_client
  node_27:
    <<: *def_client
  node_28:
    <<: *def_client
  node_29:
    <<: *def_client
  node_30:
    <<: *def_client
  node_31:
    <<: *def_client
  node_32:
    <<: *def_client
  node_33:
    <<: *def_client
  node_34:
    <<: *def_client
  node_35:
    <<: *def_client
  node_36:
    <<: *def_client
  node_37:
    <<: *def_client
  node_38:
    <<: *def_client
  node_39:
    <<: *def_client
  node_40:
    <<: *def_client
  node_41:
    <<: *def_client
  node_42:
    <<: *def_client
  node_43:
    <<: *def_client
  node_44:
    <<: *def_client
  node_45:
    <<: *def_client
  node_46:
    <<: *def_client
  node_47:
    <<: *def_client
  node_48:
    <<: *def_client
  node_49:
    <<: *def_client
  node_50:
    <<: *def_client
  node_51:
    <<: *def_client
  node_52:
    <<: *def_client
  node_53:
    <<: *def_client
  node_54:
    <<: *def_client
  node_55:
    <<: *def_client
  node_56:
    <<: *def_client
  node_57:
    <<: *def_client
  node_58:
    <<: *def_client
  node_59:
    <<: *def_client
  node_60:
    <<: *def_client
  node_61:
    <<: *def_client
  node_62:
    <<: *def_client
  node_63:
    <<: *def_client
  node_64:
    <<: *def_client
  node_65:
    <<: *def_client
  node_66:
    <<: *def_client
  node_67:
    <<: *def_client
  node_68:
    <<: *def_client
  node_69:
    <<: *def_client
  node_70:
    <<: *def_client
  node_71:
    <<: *def_client
  node_72:
    <<: *def_client
  node_73:
    <<: *def_client
  node_74:
    <<: *def_client
  node_75:
    <<: *def_client
  node_76:
    <<: *def_client
  node_77:
    <<: *def_client
  node_78:
    <<: *def_client
  node_79:
    <<: *def_client
  node_80:
    <<: *def_client
  node_81:
    <<: *def_client
  node_82:
    <<: *def_client
  node_83:
    <<: *def_client
  node_84:
    <<: *def_client
  node_85:
    <<: *def_client
  node_86:
    <<: *def_client
  node_87:
    <<: *def_client
  node_88:
    <<: *def_client
  node_89:
    <<: *def_client
  node_90:
    <<: *def_client
  node_91:
    <<: *def_client
  node_92:
    <<: *def_client
  node_93:
    <<: *def_client
  node_94:
    <<: *def_client
  node_95:
    <<: *def_client
  node_96:
    <<: *def_client
  node_97:
    <<: *def_client
  node_98:
    <<: *def_client
  node_99:
    <<: *def_client
  node_100:
    <<: *def_client
  node_101:
    <<: *def_client
  node_102:
    <<: *def_client
  node_103:
    <<: *def_client
  node_104:
    <<: *def_client
  node_105:
    <<: *def_client
  node_106:
    <<: *def_client
  node_107:
    <<: *def_client
  node_108:
    <<: *def_client
  node_109:
    <<: *def_client
  node_110:
    <<: *def_client
  node_111:
    <<: *def_client
  node_112:
    <<: *def_client
  node_113:
    <<: *def_client
  node_114:
    <<: *def_client
  node_115:
    <<: *def_client
  node_116:
    <<: *def_client
  node_117:
    <<: *def_client
  node_118:
    <<: *def_client
  node_119:
    <<: *def_client
  node_120:
    <<: *def_client
  node_121:
    <<: *def_client
  node_122:
    <<: *def_client
  node_123:
    <<: *def_client
  node_124:
    <<: *def_client
  node_125:
    <<: *def_client
  node_126:
    <<: *def_client
  node_127:
    <<: *def_client
  node_128:
    <<: *def_client
  node_129:
    <<: *def_client
  node_130:
    <<: *def_client
  node_131:
    <<: *def_client
  node_132:
    <<: *def_client
  node_133:
    <<: *def_client
  node_134:
    <<: *def_client
  node_135:
    <<: *def_client
  node_136:
    <<: *def_client
  node_137:
    <<: *def_client
  node_138:
    <<: *def_client
  node_139:
    <<: *def_client
  node_140:
    <<: *def_client
  node_141:
    <<: *def_client
  node_142:
    <<: *def_client
  node_143:
    <<: *def_client
  node_144:
    <<: *def_client
  node_145:
    <<: *def_client
  node_146:
    <<: *def_client
  node_147:
    <<: *def_client
  node_148:
    <<: *def_client
  node_149:
    <<: *def_client
  node_150:
    <<: *def_client
  node_151:
    <<: *def_client
  node_152:
    <<: *def_client
  node_153:
    <<: *def_client
  node_154:
    <<: *def_client
  node_155:
    <<: *def_client
  node_156:
    <<: *def_client
  node_157:
    <<: *def_client
  node_158:
    <<: *def_client
  node_159:
    <<: *def_client
  node_160:
    <<: *def_client
  node_161:
    <<: *def_client
  node_162:
    <<: *def_client
  node_163:
    <<: *def_client
  node_164:
    <<: *def_client
  node_165:
    <<: *def_client
  node_166:
    <<: *def_client
  node_167:
    <<: *def_client
  node_168:
    <<: *def_client
  node_169:
    <<: *def_client
  node_170:
    <<: *def_client
  node_171:
    <<: *def_client
  node_172:
    <<: *def_client
  node_173:
    <<: *def_client
  node_174:
    <<: *def_client
  node_175:
    <<: *def_client
  node_176:
    <<: *def_client
  node_177:
    <<: *def_client
  node_178:
    <<: *def_client
  node_179:
    <<: *def_client
  node_180:
    <<: *def_client
  node_181:
    <<: *def_client
  node_182:
    <<: *def_client
  node_183:
    <<: *def_client
  node_184:
    <<: *def_client
  node_185:
    <<: *def_client
  node_186:
    <<: *def_client
  node_187:
    <<: *def_client
  node_188:
    <<: *def_client
  node_189:
    <<: *def_client
  node_190:
    <<: *def_client
  node_191:
    <<: *def_client
  node_192:
    <<: *def_client
  node_193:
    <<: *def_client
  node_194:
    <<: *def_client
  node_195:
    <<: *def_client
  node_196:
    <<: *def_client
  node_197:
    <<: *def_client
  node_198:
    <<: *def_client
  node_199:
    <<: *def_client

workers:
  node_0:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - node_0
      - node_1
      - node_2
      - node_3
      - node_4
      - node_5
      - node_6
      - node_7
      - node_8
      - node_9
      - node_10
      - node_11
      - node_12
      - node_13
      - node_14
      - node_15
      - node_16
      - node_17
      - node_18
      - node_19
      - node_20
      - node_21
      - node_22
      - node_23
      - node_24
      - node_25
      - node_26
      - node_27
      - node_28
      - node_29
      - node_30
      - node_31
      - node_32
      - node_33
      - node_34
      - node_35
      - node_36
      - node_37
      - node_38
      - node_39
      - node_40
      - node_41
      - node_42
      - node_43
      - node_44
      - node_45
      - node_46
      - node_47
      - node_48
      - node_49
      # - node_50
      # - node_51
      # - node_52
      # - node_53
      # - node_54
      # - node_55
      # - node_56
      # - node_57
      # - node_58
      # - node_59
      # - node_60
      # - node_61
      # - node_62
      # - node_63
      # - node_64
      # - node_65
      # - node_66
      # - node_67
      # - node_68
      # - node_69
      # - node_70
      # - node_71
      # - node_72
      # - node_73
      # - node_74
      # - node_75
      # - node_76
      # - node_77
      # - node_78
      # - node_79
      # - node_80
      # - node_81
      # - node_82
      # - node_83
      # - node_84
      # - node_85
      # - node_86
      # - node_87
      # - node_88
      # - node_89
      # - node_90
      # - node_91
      # - node_92
      # - node_93
      # - node_94
      # - node_95
      # - node_96
      # - node_97
      # - node_98
      # - node_99
      # - node_100
      # - node_101
      # - node_102
      # - node_103
      # - node_104
      # - node_105
      # - node_106
      # - node_107
      # - node_108
      # - node_109
      # - node_110
      # - node_111
      # - node_112
      # - node_113
      # - node_114
      # - node_115
      # - node_116
      # - node_117
      # - node_118
      # - node_119
      # - node_120
      # - node_121
      # - node_122
      # - node_123
      # - node_124
      # - node_125
      # - node_126
      # - node_127
      # - node_128
      # - node_129
      # - node_130
      # - node_131
      # - node_132
      # - node_133
      # - node_134
      # - node_135
      # - node_136
      # - node_137
      # - node_138
      # - node_139
      # - node_140
      # - node_141
      # - node_142
      # - node_143
      # - node_144
      # - node_145
      # - node_146
      # - node_147
      # - node_148
      # - node_149
      # - node_150
      # - node_151
      # - node_152
      # - node_153
      # - node_154
      # - node_155
      # - node_156
      # - node_157
      # - node_158
      # - node_159
      # - node_160
      # - node_161
      # - node_162
      # - node_163
      # - node_164
      # - node_165
      # - node_166
      # - node_167
      # - node_168
      # - node_169
      # - node_170
      # - node_171
      # - node_172
      # - node_173
      # - node_174
      # - node_175
      # - node_176
      # - node_177
      # - node_178
      # - node_179
      # - node_180
      # - node_181
      # - node_182
      # - node_183
      # - node_184
      # - node_185
      # - node_186
      # - node_187
      # - node_188
      # - node_189
      # - node_190
      # - node_191
      # - node_192
      # - node_193
      # - node_194
      # - node_195
      # - node_196
      # - node_197
      # - node_198
      # - node_199

    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

job_params:
  rounds: 200
