dataset:
  cluster_configs:
    - &dataset_default
      dataset: cifar10_torch
      distribution:
        # client_weights:
        #   - 0.5
        #   - 0.5
        extra_params:
          diritchlet:
            alpha: 0.1
            seed: 10
        train_test_split:
          train: 0.8
          test: 0.2

consensus:
  - &default_2_3
    runnable: majority_2_3

training:
  client_configs:
    - &cifar_train_def
      learning_rate: 0.001
      batch_size: 64
      local_epochs: 5
      extra_params:
        fed_prox:
          mu: 0.01
        moon:
          temp: 0.5
          mu: 5.0
        lr_decay: 1

  worker_configs:
    - &fed_avg_def
      batch_size: 64
      extra_params:
        fed_avg_momentum: 0.9

model_params:
  - &cifar_simple_cnn
    strategy: cifar10_cnn_fedavgm

client_configs:
  - &def_client
    model_params:
      <<: *cifar_simple_cnn
    train_params:
      <<: *cifar_train_def
    dataset_params:
      <<: *dataset_default

worker_configs:
  - &def_worker
    model_params:
      <<: *cifar_simple_cnn
    aggregator_params:
      <<: *fed_avg_def
    dataset_params:
      <<: *dataset_default

clients:
  node_0:
    <<: *def_client
  node_1:
    <<: *def_client
  node_2:
    <<: *def_client
  node_3:
    <<: *def_client
  node_4:
    <<: *def_client
  node_5:
    <<: *def_client
  node_6:
    <<: *def_client
  node_7:
    <<: *def_client
  node_8:
    <<: *def_client
  node_9:
    <<: *def_client
#   node_10:
#     <<: *def_client
#   node_11:
#     <<: *def_client
#   node_12:
#     <<: *def_client
#   node_13:
#     <<: *def_client
#   node_14:
#     <<: *def_client
#   node_15:
#     <<: *def_client
#   node_16:
#     <<: *def_client
#   node_17:
#     <<: *def_client
#   node_18:
#     <<: *def_client
#   node_19:
#     <<: *def_client
#   node_20:
#     <<: *def_client
#   node_21:
#     <<: *def_client
#   node_22:
#     <<: *def_client
#   node_23:
#     <<: *def_client
#   node_24:
#     <<: *def_client
#   node_25:
#     <<: *def_client
#   node_26:
#     <<: *def_client
#   node_27:
#     <<: *def_client
#   node_28:
#     <<: *def_client
#   node_29:
#     <<: *def_client
workers:
  node_0:
    <<: *def_worker

clusters:
  cluster_0:
    upstream_cluster: null
    clients:
      - node_0
      - node_1
      - node_2
      - node_3
      - node_4
      - node_5
      - node_6
      - node_7
      - node_8
      - node_9
      # - node_10
      # - node_11
      # - node_12
      # - node_13
      # - node_14
      # - node_15
      # - node_16
      # - node_17
      # - node_18
      # - node_19
      # - node_20
      # - node_21
      # - node_22
      # - node_23
      # - node_24
      # - node_25
      # - node_26
      # - node_27
      # - node_28
      # - node_29
    workers:
      - node_0
    consensus_params:
      <<: *default_2_3
    train_params:
      cluster_epochs: 1
    dataset_params:
      <<: *dataset_default

job_params:
  rounds: 150
